version: '3' 

services:
  go: # サービス名
    container_name: go
    build: # ビルドに使うDockerファイルのパス
      context: .
      dockerfile: ./go/build/Dockerfile
    volumes: # マウントディレクトリ
      - ./go/src/catan:/go/src/catan
      - ~/.gitconfig:/root/.gitconfig
    tty: true
    env_file: # .envファイル
      - ./go/build/.go_env
    environment:
      - TZ=Asia/Tokyos

  next:
    container_name: next
    build: 
      context: .
      dockerfile: ./next/build/Dockerfile
    volumes:
      - ./next/src:/src 
    ports:
      - "3000:3000"
    command: sh -c "npm run dev"
    stdin_open: true
    tty: true